version: '3.8'

services:
    cpp:
        build:
            context: . 
            dockerfile: docker/cpp/Dockerfile
        stdin_open: true
        tty: true
        volumes:
            - ./src:/workspace
